### ISSUE TITLE
Add more information to "System Operations" page

### ISSUE THREAD

**Issue by MasterOdin** [hubbcaps/gazee#18]
Couple of ideas for how I'd want to improve and extend the "System Operations" page, let me know what you think and I'll add either/both/none.

1. It seems to me that that'd it'd maybe be beneficial to display the version of Gazee that's running (even if its the git commit and date of it) as well as the version of python running under the System Operations tab.
2. Display alert (or something) when hitting the "Update Server" button for what happens. Right now, there's no indication on whether a) there was a new version, b) it was applied, c) server is restarting. At the very least, I'd want an alert that said either "Update applied, restarting server." or "No update found"

**Comment by hubbcaps** [comment]
I had these on my list to pound out sometime this week. You're completely right in that both of those are needed, my inital attempts at it got halted when I couldn't get a nice splash screen working while the server restarted for the various options.

If you have some ideas for how to implement I would absolutely love to see them.

**Comment by MasterOdin** [comment]
Ideally, for alerting the user, I think for all of the operations would be to use something like [bootstrap alerts](https://www.w3schools.com/bootstrap/bootstrap_alerts.asp) to show the results of hitting the three buttons on that page, and then just have a "Refresh this page" when you restart/update the server (there's no real value in a splash screen for actions that are relatively quick).

I'd probably recommend actually that it'd be nice for all of the ajax buttons on that page to show an alert of some sort on completion of the ajax call.

**Comment by hubbcaps** [comment]
I can definitely get behind that. I'd probably go with [Materialize dialogs](http://materializecss.com/dialogs.html) just because I'm already using materialize for everything, so it'd make sense to maintain consistency there, although I do like the color schemes and look of the bootstrap ones, so feel free to choose whatever you wish if you want to implement this.

I'm brand new into touching ajax so I hadn't really looked into having actions upon a complete request from them, but you are right in that that would be the best time to execute the alert and base it on the reponse back.
