### ISSUE TITLE
Cannot change password for all users

### ISSUE THREAD

**Issue by MasterOdin** [hubbcaps/gazee#20]
If you go to Settings -> User Settings, you are only presented with one field for changing a password for the current logged in admin user. This means that users cannot change their password currently.

**Comment by hubbcaps** [comment]
Unfortunately by current design users won't be able to change passwords, at all. This is because they aren't given the option to view the settings page. 

Perhaps I can come up with a way to give them a limited selection settings page, but currently they are locked out because almost all settings are server wide types of stuff such as themeing and library paths etc.

Admins however should be able to change their passwords when logged in and navigating to the settings page.

If this is not the case, then I likely screwed up the UPDATE statement in the changePassword function to search all columns rather than just username column and it's finding the first admin each time. I'll take a look into this when I get home from work. Thank you for reporting.

**Comment by hubbcaps** [comment]
Ok, I just verified that other Admins are indeed able to change their own passwords easily enough and it applies.

In thinking about this since you opened it I've come to two possibilities for normal user password changes that don't include deleting the user and readding, because that is not user friendly.

1. Add an additional field under User Settings that takes a name and allow admins to reset everyone, including their own passwords using this.

This is my favored option as it keeps control in the hands of the admins.

2. Add a new settings page specifically geared towards normal users. Really the only thing that would be present here would be a password reset field at the moment. 

This is my least favored option, specifically cause I know users like to get lazy about password reuse, bad practices, etc, and I don't want to force my idea of a good password policy into the code, and I also think it's over kill to build in a password policy manager into the application.


If you have any other ideas, I'd love to hear them. Otherwise I'll get started on option one.

**Comment by hubbcaps** [comment]
PR #23 implements the username field so we can change users passwords after the fact. Side effect of this is any other admins will be able to in effect change your password. 

As long as you have system access to change it in the DB, this isn't a problem, but still, a bit inconvienent if you trust the wrong person.

Definitely some room for improvement.
